### ISSUE TITLE
블로그 초기 구성

### ISSUE THREAD

**Issue by hajun-myoung** [hajun-myoung/code-or-death#3]
# Purpose
블로그에 학습 내용을 업데이트 하기 이전에, 구성해 놓아햐 하는 요소들을 트래킹하기 위해 만든 이슈임

## Todo
- [x] 홈페이지 구성
- [x] 폴더 구조 결정
- [x] 네비게이션 바, 사이드 바 구성
- [ ] 가이드 페이지 작성
  - [x] 기여하는 법(pull request 관련)
  - [x] `config.ts` 파일 수정법
  - [x] 문서작성 가이드
  - [ ] 커밋 메시지 규칙
- [ ] 파비콘 적용

## Close
모든 todo가 완료되면 클로즈
